'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { generateRoadmap, RoadmapItem } from '@/lib/mockData';
import { 
  Sparkles, 
  BookOpen, 
  ArrowRight, 
  RefreshCw, 
  Copy, 
  Check 
} from 'lucide-react';

export default function RoadmapGenerator() {
  const [goal, setGoal] = useState('Build AI SaaS');
  const [level, setLevel] = useState('Beginner');
  const [industry, setIndustry] = useState('Software Engineering');
  const [budget, setBudget] = useState('Free');
  
  const [roadmap, setRoadmap] = useState<RoadmapItem[] | null>(null);
  const [completedSteps, setCompletedSteps] = useState<Record<string, boolean>>({});
  const [copied, setCopied] = useState(false);

  // Generate roadmap handler
  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    const generated = generateRoadmap(goal, level, industry, budget);
    setRoadmap(generated);
    setCompletedSteps({}); // Reset progress
  };

  // Toggle step completion
  const toggleStep = (week: string) => {
    setCompletedSteps(prev => ({
      ...prev,
      [week]: !prev[week]
    }));
  };

  // Copy markdown roadmap to clipboard
  const handleCopyMarkdown = () => {
    if (!roadmap) return;
    
    let md = `# Personal AI Learning Roadmap: ${goal}\n\n`;
    md += `**Skill Level**: ${level} | **Industry**: ${industry} | **Budget**: ${budget}\n\n`;
    md += `*Generated by AI Navigator*\n\n---\n\n`;
    
    roadmap.forEach(item => {
      md += `## ${item.week}: ${item.title}\n`;
      md += `${item.description}\n\n`;
      md += `**Recommended Tools:**\n`;
      item.toolRecommendations.forEach(tool => {
        md += `- ${tool}\n`;
      });
      md += `\n`;
    });

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-10 pb-16">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-3xl font-extrabold tracking-tight text-white md:text-4xl bg-gradient-to-r from-white via-slate-200 to-blue-400 bg-clip-text text-transparent">
          AI Roadmap Generator
        </h1>
        <p className="text-gray-400 text-sm mt-1 max-w-2xl leading-relaxed">
          Specify your objectives, skill level, and industry targets to construct a custom-tailored weekly learning path.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column: Form Parameters */}
        <div className="lg:col-span-4">
          <form onSubmit={handleGenerate} className="glass-card p-6 rounded-2xl border border-white/5 space-y-6">
            <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
              <Sparkles className="text-blue-400" size={15} /> Setup Parameters
            </h2>

            {/* Goal Input */}
            <div className="space-y-2">
              <label className="text-xs text-gray-400 font-semibold block">Primary Goal</label>
              <select
                value={goal}
                onChange={(e) => setGoal(e.target.value)}
                className="w-full text-xs bg-zinc-950 border border-white/10 text-white p-3.5 rounded-xl focus:outline-none focus:border-blue-500 font-semibold transition-colors"
              >
                <option value="Build AI SaaS">Build AI SaaS / Web Application</option>
                <option value="Learn Machine Learning">Learn Machine Learning & Foundations</option>
                <option value="Research & RAG">Research & RAG Pipelines</option>
                <option value="Automate Workflows">Automate Office & Startup Workflows</option>
              </select>
            </div>

            {/* Skill Level Selection */}
            <div className="space-y-2">
              <label className="text-xs text-gray-400 font-semibold block">Skill Level</label>
              <div className="grid grid-cols-3 gap-2">
                {['Beginner', 'Intermediate', 'Advanced'].map((lvl) => (
                  <button
                    key={lvl}
                    type="button"
                    onClick={() => setLevel(lvl)}
                    className={`py-2.5 rounded-xl text-xs font-semibold border transition-all ${
                      level === lvl
                        ? 'bg-blue-600/10 border-blue-500 text-white'
                        : 'bg-transparent border-white/5 text-gray-400 hover:text-white hover:bg-white/[0.01]'
                    }`}
                  >
                    {lvl}
                  </button>
                ))}
              </div>
            </div>

            {/* Industry focus */}
            <div className="space-y-2">
              <label className="text-xs text-gray-400 font-semibold block">Industry Context</label>
              <select
                value={industry}
                onChange={(e) => setIndustry(e.target.value)}
                className="w-full text-xs bg-zinc-950 border border-white/10 text-white p-3.5 rounded-xl focus:outline-none focus:border-blue-500 font-semibold transition-colors"
              >
                <option value="Software Engineering">Software Engineering</option>
                <option value="Design & Creative">Design & Creative</option>
                <option value="Product & Business">Product & Business</option>
                <option value="Healthcare & Life Sciences">Healthcare & Life Sciences</option>
                <option value="Education & Research">Education & Research</option>
              </select>
            </div>

            {/* Budget constraint */}
            <div className="space-y-2">
              <label className="text-xs text-gray-400 font-semibold block">API & Tool Budget</label>
              <div className="grid grid-cols-2 gap-2">
                {['Free', 'Flexible'].map((bdg) => (
                  <button
                    key={bdg}
                    type="button"
                    onClick={() => setBudget(bdg)}
                    className={`py-2.5 rounded-xl text-xs font-semibold border transition-all ${
                      budget === bdg
                        ? 'bg-blue-600/10 border-blue-500 text-white'
                        : 'bg-transparent border-white/5 text-gray-400 hover:text-white hover:bg-white/[0.01]'
                    }`}
                  >
                    {bdg === 'Free' ? 'Free Tools' : 'Paid APIs'}
                  </button>
                ))}
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs transition-colors glow-blue"
            >
              Generate Guide Map <ArrowRight size={14} />
            </button>
          </form>
        </div>

        {/* Right Column: Roadmap Syllabus Display */}
        <div className="lg:col-span-8">
          <AnimatePresence mode="wait">
            {roadmap ? (
              <motion.div
                key="roadmap-result"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-6"
              >
                {/* Result header options */}
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white/[0.01] border border-white/[0.05] p-5 rounded-2xl">
                  <div>
                    <h3 className="font-bold text-white text-xs uppercase tracking-wider">{goal} Syllabus</h3>
                    <p className="text-[10px] text-gray-400 font-semibold uppercase tracking-wider mt-0.5">
                      Tailored to {level} level in {industry}
                    </p>
                  </div>
                  
                  <div className="flex gap-2">
                    <button 
                      onClick={handleCopyMarkdown}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-white transition-colors"
                    >
                      {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                      <span>{copied ? 'Copied!' : 'Copy MD'}</span>
                    </button>
                    <button 
                      onClick={() => setRoadmap(null)}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-white transition-colors"
                    >
                      <RefreshCw size={14} />
                      <span>Reset</span>
                    </button>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="p-5 rounded-2xl bg-white/[0.01] border border-white/[0.04] flex items-center justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex justify-between text-xs text-gray-400 mb-2 font-semibold uppercase tracking-widest text-[9px]">
                      <span>Course Progress</span>
                      <span>
                        {Math.round((Object.values(completedSteps).filter(Boolean).length / roadmap.length) * 100)}% Completed
                      </span>
                    </div>
                    <div className="w-full bg-zinc-950 rounded-full h-1.5 overflow-hidden border border-white/[0.02]">
                      <div 
                        className="h-full bg-blue-500 transition-all duration-300 shadow-[0_0_8px_rgba(59,130,246,0.5)] rounded-full" 
                        style={{ width: `${(Object.values(completedSteps).filter(Boolean).length / roadmap.length) * 100}%` }}
                      />
                    </div>
                  </div>
                </div>

                {/* Vertical Timeline */}
                <div className="relative pl-8 space-y-6 border-l border-white/[0.04] ml-4">
                  {roadmap.map((item, idx) => {
                    const isDone = completedSteps[item.week];
                    return (
                      <motion.div 
                        key={item.week}
                        initial={{ opacity: 0, y: 15 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: idx * 0.1 }}
                        className="relative"
                      >
                        {/* Timeline Node Icon */}
                        <button 
                          onClick={() => toggleStep(item.week)}
                          className={`absolute left-0 top-1 -translate-x-[45px] w-8 h-8 rounded-full flex items-center justify-center border transition-all ${
                            isDone 
                              ? 'bg-emerald-600 border-emerald-500 text-white shadow-[0_0_12px_rgba(16,185,129,0.35)]'
                              : 'bg-zinc-950 border-white/[0.08] text-gray-500 hover:border-blue-500 hover:text-blue-400 shadow-md'
                          }`}
                        >
                          {isDone ? <Check size={14} strokeWidth={3} /> : <span className="text-[10px] font-bold">{idx + 1}</span>}
                        </button>

                        {/* Content Card */}
                        <div className={`glass-card p-6 rounded-2xl border transition-all ${
                          isDone ? 'border-emerald-500/10 opacity-70 bg-emerald-950/[0.02]' : 'border-white/5'
                        }`}>
                          <div className="flex justify-between items-start gap-4">
                            <div>
                              <span className="text-[9px] uppercase font-bold tracking-widest text-blue-400 font-mono">
                                {item.week}
                              </span>
                              <h3 className={`font-bold text-xs mt-0.5 ${isDone ? 'line-through text-gray-500' : 'text-white'}`}>
                                {item.title}
                              </h3>
                            </div>
                            
                            <button
                              onClick={() => toggleStep(item.week)}
                              className="text-xs text-gray-500 hover:text-blue-400 font-semibold"
                            >
                              {isDone ? 'Undo mark' : 'Complete step'}
                            </button>
                          </div>

                          <p className="text-xs text-gray-400 mt-2 leading-relaxed">
                            {item.description}
                          </p>

                          {/* Tool Recommendations */}
                          <div className="mt-4 flex flex-wrap gap-2 items-center">
                            <span className="text-[9px] uppercase font-bold text-gray-500 tracking-widest">Suggested Tools:</span>
                            {item.toolRecommendations.map((tool) => (
                              <span 
                                key={tool} 
                                className="text-[9px] bg-blue-500/10 border border-blue-500/20 text-blue-300 font-bold px-2 py-0.5 rounded-lg"
                              >
                                {tool}
                              </span>
                            ))}
                          </div>
                        </div>
                      </motion.div>
                    );
                  })}
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="roadmap-placeholder"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="glass-card p-12 rounded-2xl border border-white/10 text-center flex flex-col items-center justify-center py-24 space-y-4 shadow-md"
              >
                <div className="h-12 w-12 rounded-full bg-white/[0.02] flex items-center justify-center text-gray-400 border border-white/10">
                  <BookOpen size={20} />
                </div>
                <div className="max-w-xs space-y-1">
                  <h3 className="text-sm font-bold text-white">Generate Learning Path</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">
                    Adjust the parameters in the left panel and click "Generate Guide Map" to build your custom path.
                  </p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>
    </div>
  );
}
